
# Bureau of Labor and Statistics

### EDA

- **Consumer Price Index** 
- **Consumer Expenditure Survey**
- **Consumer Purchase Survey**

Dataset is comprised of components of economic effects that lead to inflation and the effects of inflation for the consumer.

This notebook will consist of performing expoloratory data analysis on the selected areas of focus. Analysis will assist in attaining greater insight of the data and how we should approach model training.
***
**Import our Libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

**Basic Pandas functions**

In [6]:
df = pd.read_csv('/Users/jasonrobinson/Documents/Projects/bls_project/data_2/SeriesReport-cpi-market-mix.48.csv')
print(df.shape)
df.T

(75, 49)

,0,1,2,3,4,5,6,7,8,9,...,65,66,67,68,69,70,71,72,73,74
Year,1948.0,1949.0,1950.0,1951.0,1952.0,1953.0,1954.0,1955.0,1956.0,1957.0,...,2013.000,2014.000,2015.000,2016.000,2017.000,2018.000,2019.000,2020.000,2021.000,2022.000
Jan_U,23.7,24.0,23.5,25.4,26.5,26.6,26.9,26.7,26.8,27.6,...,230.280,233.916,233.707,236.916,242.839,247.867,251.712,257.971,261.582,281.148
Jan_W,23.8,24.2,23.7,25.5,26.6,26.8,27.1,26.9,27.0,27.8,...,226.520,230.040,228.294,231.061,236.854,241.919,245.133,251.361,255.296,276.296
Jan_Emp,58061.0,58175.0,57635.0,59636.0,60460.0,61600.0,60024.0,60753.0,63753.0,63632.0,...,143292.000,145150.000,148145.000,150653.000,152152.000,154493.000,156614.000,158653.000,150004.000,157174.000
Jan_LF,60095.0,60771.0,61661.0,61941.0,62432.0,63439.0,63101.0,63910.0,66419.0,66428.0,...,155763.000,155352.000,157030.000,158280.000,159620.000,160998.000,163072.000,164479.000,160184.000,163687.000
Feb_U,23.5,23.8,23.5,25.7,26.3,26.5,26.9,26.7,26.8,27.7,...,232.166,234.781,234.722,237.111,243.603,248.991,252.776,258.678,263.014,NaN
Feb_W,23.6,23.9,23.6,25.9,26.5,26.7,27.1,26.9,27.0,27.9,...,228.677,230.871,229.421,230.972,237.477,242.988,246.218,251.935,256.843,NaN
Feb_Emp,58196.0,58208.0,57751.0,59661.0,60462.0,61884.0,60663.0,60727.0,63518.0,64257.0,...,143362.000,145134.000,148045.000,150939.000,152480.000,155259.000,156992.000,158866.000,150367.000,157722.000
Feb_LF,60524.0,61057.0,61687.0,61778.0,62419.0,63520.0,63994.0,63696.0,66124.0,66879.0,...,155312.000,155483.000,156644.000,158640.000,159859.000,161846.000,163114.000,164583.000,160359.000,163991.000
Mar_U,23.4,23.8,23.6,25.8,26.3,26.6,26.9,26.7,26.8,27.8,...,232.773,236.293,236.119,238.132,243.801,249.554,254.202,258.115,264.877,NaN
Mar_W,23.6,24.0,23.7,26.0,26.5,26.7,27.0,26.9,27.0,28.0,...,229.323,232.560,231.055,232.209,237.656,243.463,247.768,251.375,258.935,NaN
Mar_Emp,57671.0,58043.0,57728.0,60401.0,59908.0,62010.0,60186.0,60964.0,63411.0,64404.0,...,143316.000,145648.000,148128.000,151218.000,153065.000,155303.000,156869.000,155599.000,150940.000,NaN
Mar_LF,60070.0,61073.0,61604.0,62526.0,61721.0,63657.0,63793.0,63882.0,66175.0,66913.0,...,155005.000,156028.000,156643.000,159179.000,160137.000,161760.000,163035.000,162764.000,160631.000,NaN
Apr_U,23.8,23.9,23.6,25.8,26.4,26.6,26.8,26.7,26.9,27.9,...,232.531,237.072,236.599,239.261,244.524,250.546,255.548,256.389,267.054,NaN
Apr_W,23.9,24.0,23.7,26.0,26.6,26.8,27.0,26.9,27.0,28.1,...,228.949,233.443,231.520,233.438,238.432,244.607,249.332,249.515,261.237,NaN
Apr_Emp,58291.0,57747.0,58583.0,59889.0,59909.0,61444.0,60185.0,61515.0,63614.0,64047.0,...,143635.000,145667.000,148511.000,151074.000,153255.000,155362.000,156744.000,133320.000,151259.000,NaN
Apr_LF,60677.0,61007.0,62158.0,61808.0,61720.0,63167.0,63934.0,64564.0,66264.0,66647.0,...,155394.000,155369.000,157060.000,159141.000,160345.000,161809.000,162642.000,156358.000,160978.000,NaN
May_U,23.9,23.8,23.7,25.9,26.4,26.7,26.9,26.7,27.0,28.0,...,232.945,237.900,237.805,240.229,244.733,251.588,256.092,256.394,269.195,NaN
May_W,24.1,24.0,23.8,26.1,26.6,26.8,27.1,26.9,27.2,28.1,...,229.399,234.216,232.908,234.436,238.609,245.770,249.871,249.521,263.612,NaN
May_Emp,57854.0,57552.0,58649.0,60188.0,60195.0,61019.0,59908.0,61634.0,63861.0,63985.0,...,143882.000,145825.000,148817.000,151132.000,153069.000,155694.000,156868.000,137182.000,151550.000,NaN
May_LF,59972.0,61259.0,62083.0,62044.0,62058.0,62615.0,63675.0,64381.0,66722.0,66695.0,...,155536.000,155684.000,157651.000,158784.000,160068.000,161882.000,162803.000,158122.000,160801.000,NaN
Jun_U,24.1,23.9,23.8,25.9,26.5,26.8,26.9,26.7,27.2,28.1,...,233.504,238.343,238.638,241.018,244.955,251.989,256.143,257.797,271.696,NaN
Jun_W,24.2,24.0,24.0,26.1,26.7,26.9,27.1,26.9,27.3,28.3,...,230.002,234.702,233.804,235.289,238.813,246.196,249.747,251.054,266.412,NaN
Jun_Emp,58743.0,57172.0,59052.0,59620.0,60219.0,61456.0,59792.0,61781.0,63820.0,64196.0,...,143999.000,146247.000,148816.000,151223.000,153318.000,155734.000,157123.000,142218.000,151612.000,NaN
Jun_LF,60957.0,60948.0,62419.0,61615.0,62103.0,63063.0,63343.0,64482.0,66702.0,67052.0,...,155749.000,155707.000,157062.000,158967.000,160192.000,162180.000,163029.000,159834.000,161114.000,NaN
Jul_U,24.4,23.7,24.1,25.9,26.7,26.8,26.9,26.8,27.4,28.3,...,233.596,238.250,238.654,240.628,244.786,252.006,256.571,259.101,273.003,NaN
Jul_W,24.5,23.8,24.2,26.1,26.9,27.0,27.1,27.0,27.5,28.4,...,230.084,234.525,233.806,234.771,238.617,246.155,250.236,252.636,267.789,NaN
Jul_Emp,58968.0,57190.0,59001.0,60156.0,59971.0,61397.0,59643.0,62513.0,63800.0,64540.0,...,144264.000,146399.000,148830.000,151554.000,153569.000,156115.000,157488.000,143727.000,152704.000,NaN
Jul_LF,61181.0,61301.0,62121.0,62106.0,61962.0,63057.0,63302.0,65145.0,66752.0,67336.0,...,155599.000,156007.000,156997.000,159194.000,160462.000,162288.000,163472.000,160015.000,161375.000,NaN
Aug_U,24.5,23.8,24.3,25.9,26.7,26.9,26.9,26.8,27.3,28.3,...,233.877,237.852,238.316,240.849,245.519,252.146,256.558,259.918,273.567,NaN
Aug_W,24.6,23.9,24.4,26.1,26.9,27.1,27.1,26.9,27.5,28.5,...,230.359,234.030,233.366,234.904,239.448,246.336,250.112,253.597,268.387,NaN
Aug_Emp,58456.0,57397.0,59797.0,59994.0,59790.0,61151.0,59853.0,62797.0,63972.0,63959.0,...,144326.000,146530.000,149181.000,151779.000,153503.000,155512.000,157780.000,147176.000,153167.000,NaN
Aug_LF,60806.0,61590.0,62596.0,61927.0,61877.0,62816.0,63707.0,65581.0,66673.0,66706.0,...,155605.000,156130.000,157172.000,159562.000,160586.000,161679.000,163774.000,160707.000,161505.000,NaN
Sep_U,24.5,23.9,24.4,26.1,26.7,26.9,26.8,26.9,27.4,28.3,...,234.149,238.031,237.945,241.428,246.819,252.439,256.759,260.280,274.310,NaN
Sep_W,24.6,24.0,24.6,26.3,26.9,27.1,27.0,27.0,27.5,28.5,...,230.537,234.170,232.661,235.495,240.939,246.565,250.251,254.004,269.086,NaN
Sep_Emp,58513.0,57584.0,59575.0,59713.0,60521.0,60906.0,60282.0,62950.0,64079.0,64121.0,...,144418.000,146778.000,148826.000,151761.000,154286.000,155970.000,158249.000,147569.000,153806.000,NaN
Sep_LF,60815.0,61633.0,62349.0,61780.0,62457.0,62727.0,64209.0,65628.0,66714.0,67064.0,...,155687.000,156040.000,156733.000,159714.000,161140.000,162035.000,164015.000,160153.000,161471.000,NaN
Oct_U,24.4,23.7,24.6,26.2,26.7,27.0,26.8,26.9,27.5,28.3,...,233.546,237.433,237.838,241.729,246.663,252.885,257.346,260.388,276.589,NaN
Oct_W,24.5,23.9,24.7,26.4,26.9,27.2,26.9,27.0,27.7,28.5,...,229.735,233.229,232.373,235.732,240.573,247.038,250.894,254.076,271.552,NaN
Oct_Emp,58387.0,57269.0,59803.0,60010.0,60132.0,60893.0,60270.0,62991.0,63975.0,64046.0,...,143537.000,147427.000,149246.000,151793.000,153609.000,156294.000,158356.000,149719.000,154234.000,NaN
Oct_LF,60646.0,62185.0,62428.0,62204.0,61971.0,62867.0,63936.0,65821.0,66546.0,67066.0,...,154673.000,156417.000,157167.000,159605.000,160309.000,162525.000,164336.000,160834.000,161610.000,NaN
Nov_U,24.2,23.8,24.7,26.4,26.7,26.9,26.8,26.9,27.5,28.4,...,233.069,236.151,237.336,241.353,246.669,252.038,257.208,260.229,277.948,NaN
Nov_W,24.4,23.9,24.8,26.5,26.9,27.1,27.0,27.1,27.7,28.6,...,229.133,231.551,231.721,235.215,240.666,245.933,250.644,253.826,273.042,NaN
Nov_Emp,58417.0,58009.0,59697.0,59836.0,60748.0,60738.0,60357.0,63257.0,63796.0,63669.0,...,144479.000,147404.000,149463.000,151954.000,153805.000,156606.000,158504.000,149761.000,155324.000,NaN
Nov_LF,60702.0,62005.0,62286.0,62014.0,62491.0,62949.0,63759.0,66037.0,66657.0,67123.0,...,155265.000,156494.000,157463.000,159506.000,160579.000,162738.000,164434.000,160539.000,162126.000,NaN
Dec_U,24.1,23.6,25.0,26.5,26.7,26.9,26.7,26.8,27.6,28.4,...,233.049,234.812,236.525,241.432,246.524,251.233,256.974,260.474,278.802,NaN
Dec_W,24.2,23.8,25.1,26.6,26.9,27.0,26.9,27.0,27.8,28.6,...,229.174,229.909,230.791,235.390,240.526,244.786,250.452,254.081,273.925,NaN
Dec_Emp,58740.0,57845.0,59429.0,60497.0,60954.0,59977.0,60116.0,63684.0,63910.0,63922.0,...,144778.000,147615.000,150128.000,152157.000,153904.000,156767.000,158772.000,149883.000,155975.000,NaN
Dec_LF,61169.0,61908.0,62068.0,62457.0,62621.0,62795.0,63312.0,66445.0,66700.0,67398.0,...,155182.000,156332.000,158035.000,159678.000,160535.000,163146.000,164633.000,160671.000,162294.000,NaN

**Summary Statistics**

**Basic quick visualization**

**Import our Libraries**

**Import our Libraries**

**Import our Libraries**